services:
  - type: web
    name: advance-notes-backend
    runtime: python310
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --bind 0.0.0.0:8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10